apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: finance-manager-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: finance-manager-app
  namespaceSelector:
    matchNames:
      - finance-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s